export type ComplaintUrgency = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export type ComplaintStatus =
  | 'REGISTERED'
  | 'UNDER_PROCESSING'
  | 'FORWARDED'
  | 'ON_HOLD'
  | 'COMPLETED'
  | 'REJECTED'
  | 'ESCALATED_TO_MUNICIPAL_LEVEL'
  | 'ESCALATED_TO_STATE_LEVEL'
  | 'DELETED';

export type Department =
  | 'INFRASTRUCTURE'
  | 'EDUCATION'
  | 'REVENUE'
  | 'HEALTH'
  | 'WATER_SUPPLY_SANITATION'
  | 'ELECTRICITY_POWER'
  | 'TRANSPORTATION'
  | 'MUNICIPAL_SERVICES'
  | 'POLICE_SERVICES'
  | 'ENVIRONMENT'
  | 'HOUSING_URBAN_DEVELOPMENT'
  | 'SOCIAL_WELFARE'
  | 'PUBLIC_GRIEVANCES';